//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinLog
    {
        public int BinLogId { get; set; }
        public int BinId { get; set; }
        public double CurrentCapacity { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Bin Bin { get; set; }
    }
}
