//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WasteManagerEntities : DbContext
    {
        public WasteManagerEntities()
            : base("name=WasteManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinLog> BinLogs { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<LUT_Area> LUT_Area { get; set; }
        public virtual DbSet<LUT_BinType> LUT_BinType { get; set; }
        public virtual DbSet<LUT_TruckType> LUT_TruckType { get; set; }
        public virtual DbSet<LUT_Weekdays> LUT_Weekdays { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<WasteTransferLog> WasteTransferLogs { get; set; }
        public virtual DbSet<Bin> Bins { get; set; }
    
        public virtual ObjectResult<spBin_GetBinListFullDetails_Result> spBin_GetBinListFullDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBin_GetBinListFullDetails_Result>("spBin_GetBinListFullDetails");
        }
    
        public virtual ObjectResult<spTruck_GetTruckListFullDetails_Result> spTruck_GetTruckListFullDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTruck_GetTruckListFullDetails_Result>("spTruck_GetTruckListFullDetails");
        }
    }
}
